FROM archlinux:base
LABEL org.opencontainers.image.authors="githubfoam"

RUN pacman -Syu --noconfirm
RUN pacman -S ansible --noconfirm && ansible --version

#testing
RUN ansible --version

WORKDIR /home/ansible