#https://hub.docker.com/_/clearlinux
FROM clearlinux:latest    
LABEL org.opencontainers.image.authors="githubfoam"

#https://docs.ansible.com/ansible/latest/installation_guide/intro_installation.html#installing-ansible-on-clear-linux
#Ansible and its dependencies are available as part of the sysadmin host management bundle
RUN swupd bundle-add sysadmin-hostmgmt 
# Update of the software will be managed by the swupd tool
RUN swupd update

#testing
RUN ansible --version

