FROM ubuntu:21.04    
LABEL org.opencontainers.image.authors="githubfoam"

RUN apt-get update && apt-get install -y --no-install-recommends software-properties-common
RUN add-apt-repository --yes --update ppa:ansible/ansible & apt-get install ansible -y 

#testing
RUN ansible --version

